### ISSUE TITLE
TypeError: _reactNativeMmkv.MMKV.set is not a function

### ISSUE THREAD

**Issue by alexkendall** [mrousavy/react-native-mmkv#1]
Steps
`yarn install`
`cd ios && pod install`

import {MMKV} from 'react-native-mmkv
...
MMKV.set(email, LAST_TYPED_EMAIL)

After entering that code I get the error TypeError: _reactNativeMmkv.MMKV.set is not a function. Furthermore, after logging the MKV object, I have attached the following screen. It seems there is an issue with the native code and JS not being linked as all the methods are undefined.

![Screen Shot 2021-02-24 at 9 16 57 PM](https://user-images.githubusercontent.com/8241866/109093035-a69fa200-76e5-11eb-8d2e-173518e5eaca.png)

**Comment by KingAmo** [comment]
same here
![image](https://user-images.githubusercontent.com/29938227/109098399-38e28d00-775c-11eb-9566-211ddbce36c7.png)

**Comment by KingAmo** [comment]
enable hermes && do not use chrome debugger fixed the error

**Comment by mrousavy** [comment]
Yes, so you cannot use the Chrome debugger when using JSI. This is due to the fact that when you are debugging with Chrome, your JavaScript actually does not execute on your device and therefore does not have direct access to JSI. (The bridge still works but that's another story).

So you have to use Flipper debugger, or write such good code that you have to never debug again 🤗

**Comment by douugbr** [comment]
I'm using hermes, not using chrome debugger but it still says the functions are undefined when I console.log the MMKV alias

![image](https://user-images.githubusercontent.com/59324692/111831893-c5e9b380-88ce-11eb-9254-0aa0aeffe8a0.png)

**Comment by mrousavy** [comment]
@douugbr which MMKV version are you on?

**Comment by douugbr** [comment]
The issue was happening on the latest 1.0.11 version, I just tried downgrading to 1.0.10 and it fixed my problem, but I'd be glad to upgrade again to help you in troubleshooting.

**Comment by mrousavy** [comment]
I'm currently investigating this and will rewrite the JSI installer to be a turbo module. That should fix it. So stay on the version that's currently working for you and watch the "Releases" section here ;)

**Comment by douugbr** [comment]
Unfortunately it fixed for a short time and just after I reloaded it, the same issue began, this is extremely weird, I tried installing even the 1.0.2 and the same issue was arising, the only explanation is something with my project setup probably

![image](https://user-images.githubusercontent.com/59324692/111840259-e455ac00-88da-11eb-8cd0-8046a83c54a3.png)

**Comment by mrousavy** [comment]
@douugbr just to confirm - does it work for you now with the latest version + the (temporary) additional installation steps for Android?

**Comment by douugbr** [comment]
@mrousavy unfortunately, due to the issues I was experiencing that day, I chose to try [ammarahm-ed's version of a MMKV RN implementation](https://github.com/ammarahm-ed/react-native-mmkv-storage), but I will install yours again in a side project to test once I have the time to, and if it works I'll let you know.

**Comment by mrousavy** [comment]
@douugbr oh yeah he also rewrote it in JSI shortly after I did 😅 
all good, use whatever you prefer
