### ISSUE TITLE
Android - package com.reactnativemmkv does not exist

### ISSUE THREAD

**Issue by swalker326** [mrousavy/react-native-mmkv#106]
React 16.13.1
MMKV 1.2.0

After adding via `yarn add react-native-mmkv` I've run pod install and everything is working correctly on IOS.

I've followed the directions in the read me. 

- added ExampleJSIPackage.java with the provided code snippet. 
- In MainApplication.java i've added the provided method. (Android studio auto completes with the package name)

Screenshots

![Screen Shot 2021-07-20 at 3 02 43 PM](https://user-images.githubusercontent.com/8460808/126388120-7e4bd711-93e1-428c-8a9e-fb6a5f0a7f25.png)

![Screen Shot 2021-07-20 at 2 59 12 PM](https://user-images.githubusercontent.com/8460808/126388026-815181c3-1b08-4084-8d9f-3a3e70088955.png)

**Comment by shamxeed** [comment]
I am having the same issue, any progress on this, please??

**Comment by shamxeed** [comment]
After going through other issues I found out that this module is not correctly auto-linked, so I followed the workaround [here](https://github.com/mrousavy/react-native-mmkv/issues/37#issue-837682715) and then after successful auto-link, my app keeps on crashing on Android and based on this [issue](https://github.com/mrousavy/react-native-mmkv/issues/98#issue-941177354), the problem is with this module's latest version, so I had to downgrade it to version 1.1.6 as of now it's working smoothly. But would like to see all these issues were been addressed, thanks to the maintainers for the hard work!!!

**Comment by mrousavy** [comment]
Yes this is an autolinking issue. I'm currently really busy with work, so use the workaround @shamxeed mentioned for now, I'll try to fix this asap!

**Comment by mrousavy** [comment]
Okay so sorry guys I had to publish a few version before I finally got it right. Take a look at v1.2.5 and let me know if that works for you now.

**Comment by shamxeed** [comment]
@mrousavy it's still crashing on start on Android.

**Comment by mrousavy** [comment]
While I already spent way too much of my free time on this issue to fix the crash for random people on the internet, I spent some more time on this yesterday and **finally fixed it**. **Check out [1.3.1](https://github.com/mrousavy/react-native-mmkv/releases/tag/v1.3.1)**. 🎉🎉🎉🎉 

If you appreciate my efforts, please consider buying me a coffee for my next late-night debug session: [**❤️ GitHub sponsors**](https://github.com/sponsors/mrousavy)

**Comment by DreamakerDimas** [comment]
It's the solution that helped in my case (react-native-mmkv v2.5.1): 
https://github.com/mrousavy/react-native-vision-camera/issues/1039#issuecomment-1198697939

, I also had Zulu on the machine.
