### ISSUE TITLE
Library not found on iOS (Linking Xcode)

### ISSUE THREAD

**Issue by IronTony** [mrousavy/react-native-mmkv#147]
Hey.
I am trying to create the IPA to test my app on a real device, but unfortunately when I try to Archive the app, during the Linking phase I get this:
![image](https://user-images.githubusercontent.com/3645225/132990296-380f2d86-baea-41f4-a060-2f89f9f5c7ac.png)

After the installation of the package, I did also "pod install" and I can see MMKV folder in my Pods folder.

I am using:
react-native-mmkv: 1.3.1
react-native: 0.64.2

**Comment by bryansum** [comment]
@IronTony This happened to me recently due to having different deployment target versions in my `Podfile` and app target. I had only updated my `Podfile` but this also needs to be set in the Xcode project configuration:

<img width="335" alt="Screen Shot 2021-09-14 at 11 13 07 PM" src="https://user-images.githubusercontent.com/49369/133364524-4db0f7fa-72e5-4547-890f-74d7c8cbf073.png">

as well as the target:

<img width="216" alt="Screen Shot 2021-09-14 at 11 14 59 PM" src="https://user-images.githubusercontent.com/49369/133364691-4411c1ea-227e-425d-a4fc-b4fdd22598e9.png">

then I was able to do an archive build successfully.

**Comment by IronTony** [comment]
Hey @bryansum. Thank you so much, I compiled just now.
My bad configuration.

Thank you so much mate
