### ISSUE TITLE
Adding Async/Promise and Callback Wrappers

### ISSUE THREAD

**Issue by fahad86** [mrousavy/react-native-mmkv#15]
People cann still have an easier option of keeping the storage calls async and this would make migration from other libraries much easier:

e.g.

```
MMKV.setAsync("key", "value")
.then(function() {});

MMKV.getStringAsync("key")
.then(function(value) {});
// OR
let value = await MMKV.getStringAsync("key")
```

**Comment by mrousavy** [comment]
Hi! I have migrated two projects from AsyncStorage to MMKV now, and I was also thinking about this.

I'm **not** doing it for the following reasons:

1. It does not make sense to have that in the library. If you want to call it that way, you can create a wrapper for the library in your project. 
2. It took me less than 4 hours for 2 quite big projects, so it isn't that difficult. I've had the help of TSC and ESLint telling me about every error (with the "no non-promise like await" rule), so that was a huge help.

Thanks!
