### ISSUE TITLE
Expo installation

### ISSUE THREAD

**Issue by samuel3105** [mrousavy/react-native-mmkv#157]
Running mmkv with Expo failed with this error :

```
Failed to create a new MMKV instance, the native initializer function does not exist.
Is the native MMKV library correctly installed?
Make sure to disable any remote debugger (e.g. Chrome) to use JSI!
```

Maybe expo doesn't support it for now? (because of JSI ?). Any clue to install it or to explain why we cannot ?

**Comment by mrousavy** [comment]
Yes, you need to have a custom app.config plugin for react-native-mmkv. (EAS or expo prebuild)
I haven't provided one yet because I'm still hoping that the API changes soon and it can be autolinked (react-native 0.67 maybe?).

I believe @axeldelafosse created a plugin for RN MMKV, can't find it right now though 🤔

**Comment by renanmav** [comment]
It would be nice to have at least an example on how to use `react-native-mmkv` with an Expo managed project.

I think we accomplish this using `app.json` plugins https://docs.expo.dev/guides/config-plugins/

**Comment by wodin** [comment]
> I believe @axeldelafosse created a plugin for RN MMKV, can't find it right now though 🤔

https://github.com/mrousavy/react-native-mmkv/issues/162#issuecomment-926422460

**Comment by renanmav** [comment]
thanks @wodin

**Comment by axeldelafosse** [comment]
Here is the latest config plugin: https://gist.github.com/axeldelafosse/8cd7274501180257ae4951a0dc8759c2

You need to create `react-native-mmkv-plugin.js` and add it to your plugins in `app.config.js`:
```
plugins: ['./react-native-mmkv-plugin.js'],
```

More info on config plugins here: https://docs.expo.dev/guides/config-plugins/

**Comment by nandorojo** [comment]
Axel also clarified that you need `"react-native-mmkv": "1.3.2"` for Expo usage.

**Comment by fristyr** [comment]
@axeldelafosse 
Hi! Thanks for your gist, 
But I am facing an error when trying to expo run:android

> Task :react-native-mmkv:generateJsonModelDebug FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build failed with an exception.

Any ideas why? Maybe I forgot to install something.

**Comment by a-eid** [comment]
I'm having the same issue on android, after trying to apply the plugin by @axeldelafosse

**Comment by AlexLup06** [comment]
Any updates on this?

**Comment by FaisalBinAhmed** [comment]
> Any updates on this? I get: Error: react-native-mmkv is not supported in Expo Go! Use EAS (`expo prebuild`) or eject to a bare workflow instead.

The library author can't do anything here. Expo needs to decide to support react-native-mmkv in the Expo Go app. Expo Go comes with select packages and dependencies.

**Comment by wodin** [comment]
@AlexLup06, while @FaisalBinAhmed is correct that this is out of `react-native-mmkv`'s control, the error message is misleading.

This will not work in Expo Go (unless the Expo team decides to include `react-native-mmkv` in Expo Go), but what you can do is create a development build and use that instead of Expo Go. A development build is basically like a custom version of Expo Go, with all of your dependencies compiled in.

**Comment by AlexLup06** [comment]
@wodin @FaisalBinAhmed 
Oh, gotcha.
Got it to work! 
Thank you for your quick responses!
