### ISSUE TITLE
Upgrading to 1.3.3 creates compile error

### ISSUE THREAD

**Issue by alexco2** [mrousavy/react-native-mmkv#177]
Hi,
after upgrading to version 1.3.3 I get the following error:
```
C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
JSI_LIB
```

Donwgrading to 1.3.2 again solves this issue.

**Comment by retyui** [comment]
the same problem

```
"react-native": "^0.63.x",
"react-native-mmkv": "^1.3.3",
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv:generateJsonModelDebug'.
> /home/i/all_work/thera/mobile-thera-app/node_modules/react-native-mmkv/android/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "reactnativemmkv" in directory /home/i/all_work/thera/mobile-thera-app/node_modules/react-native-mmkv/android


```

**Comment by retyui** [comment]
@mrousavy 



https://github.com/mrousavy/react-native-mmkv/blob/e0527fc64466b82da1b285c427a921894e3cd8b2/package.json#L69-L72

How about removing dirty versions ^^^ and use something valuable `>=0.66.0`

**Comment by alexco2** [comment]
@mrousavy no stress. I just wanted to report the issue. For me that is not a problem.

**Comment by Albermonte** [comment]
Will this ever get fixed?

**Comment by mrousavy** [comment]
@Albermonte 
> Will this ever get fixed?

As you can read in my previous comment, there is a solution for this problem. Simply use RN 0.66. In said comment, I also said that I will take a look at this when I have some free time. I didn't have free time to fix **your issues** yet, since I am busy running a company and enjoying life. Instead of rudely asking someone that provides an awesome project **for free** to fix your issues, why not try to fix it yourself and contribute to the project you are using **for free**?

**Comment by alexco2** [comment]
@mrousavy totaly agree. Your work is really bringing react-native forward. Some people do not understand what work is put into these kind of libraries and aparently do not appreciate it. This really is a downside of open-source...
As a gesture, I bought you a coffee :D

**Comment by Albermonte** [comment]
@mrousavy All I did was asking if it was going to be fixed becuase there were no new info after almost 2 months and wanted to know if you are still working on this or just ignoring the error because it works on the latest RN version.

Sorry if the message was rude or similar, not my intention.

If you have any idea why it's not working with RN <0.66 I can try to fix it and open a PR.

Cheers

**Comment by mrousavy** [comment]
All good, I'm sure it's just the form of communication, hard to tell a tone over the internet.

No, I am not currently investigating this, since react-native-mmkv is as fast as ever and works great in the `example/` app here, as well as in 3 apps I am using in production.

If you find a fix that works for you, I am very happy to test your PR if it still works in my apps, and if it does we can get that to master asap. :)

Have a nice weekend y'all

**Comment by mrousavy** [comment]
Also, thank you Alex for the Coffee. Much appreciated! 🖤

**Comment by Albermonte** [comment]
The issue is [here](https://github.com/mrousavy/react-native-mmkv/blob/0a3b07970628db40d983b990a4fa4e4c2c72a868/android/CMakeLists.txt#L34-L39)

RN < 0.66 doesn't need that block, while other libraries like [react-native-mmkv-storage
](https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/master/android/src/main/rnmmkv/CMakeLists.txt) use something like this:

```
if (JSI_LIB)
  # React Native 0.66.x and above
  find_library(
        JSI_LIB
        jsi
        PATHS ${LIBRN_DIR}
        NO_CMAKE_FIND_ROOT_PATH
  )
endif()
```

That doesn't work here, no idea why, the `JSI_LIB` var is always empty, so it will only work for RN < 0.66.

I got it working for RN 0.66 with that code but only sometimes, so will use `patch-package` with RN < 0.66 until a proper fix is  found.

If anyone wants it:

`react-native-mmkv+1.5.3.patch`
```
diff --git a/node_modules/react-native-mmkv/android/CMakeLists.txt b/node_modules/react-native-mmkv/android/CMakeLists.txt
index 8784d6b..434d8b1 100644
--- a/node_modules/react-native-mmkv/android/CMakeLists.txt
+++ b/node_modules/react-native-mmkv/android/CMakeLists.txt
@@ -31,12 +31,7 @@ find_library(
         log-lib
         log
 )
-find_library(
-        JSI_LIB
-        jsi
-        PATHS ${LIBRN_DIR}
-        NO_CMAKE_FIND_ROOT_PATH
-)
+
 find_library(
         REACT_NATIVE_JNI_LIB
         reactnativejni

```

**Comment by todorone** [comment]
Thaks for the solution, @Albermonte

**Comment by flyskywhy** [comment]
[Add support for react-native 0.71 to fix `CMake Error: The following ariables are used in this project, but they are set to NOTFOUND. FBJNI_LIB`](https://github.com/flyskywhy/playtorch/commit/ce55e974dc4e29622039b04ecf6efc62ab205c6b)
