### ISSUE TITLE
Would you accept a PR to add defaults?

### ISSUE THREAD

**Issue by ferrannp** [mrousavy/react-native-mmkv#230]
So if I do:

```js
const theme = storage.getString('my-key', 'light');
```

If `my-key` is not present, then instead of returning `undefined`, it would return `light`.

Let me know, happy to add that. Thank you for all your libraries btw, you are awesome.

**Comment by mrousavy** [comment]
Hi! Thanks. That's something I don't want in the library, passing parameters as default values is a bit confusing. Why not just do:

```ts
const theme = storage.getString('my-key') ?? 'light';
```
?

**Comment by ferrannp** [comment]
Hey! That's ok (that is what I do right now). I guess I was influenced for the time I was using `SharedPreferences` directly from Android: [getString(String key, String defValue)](https://developer.android.com/reference/android/content/SharedPreferences#getString(java.lang.String,%20java.lang.String)).

All clear then, no PR 👍 .

**Comment by ferrannp** [comment]
@mrousavy I just realised that:

```js
storage.getBoolean('some-key') ?? true;
```

This will return `false` even if `some-key` is not in the storage as `getBoolean` seems to return `false` even if the key is not present. How would you handle this case?

**Comment by mrousavy** [comment]
Yeah that's indeed an interesting case. This is a problem with the native MMKV library, since that returns `false` on boolean keys that don't exist. Not `null`.

So either you add an additional `has(..)` check before your `getBoolean` call, or you shape your storage structure to assume false by default, whether the key exists or not. (e.g.: `isNotLoggedIn` -> `isLoggedIn`, assume `false` by default)
