### ISSUE TITLE
[question]Access Storage from Native module

### ISSUE THREAD

**Issue by mtroskot** [mrousavy/react-native-mmkv#311]
How can I access MMKV storage from a native module in Android/iOS ?

On Android I've added in build.gradle
`implementation 'com.tencent:mmkv:1.2.12'`

and from the native module I call
```
   String rootDir = MMKV.initialize(reactContext);
   MMKV mmkv = MMKV.defaultMMKV();
   Log.d("storage", mmkv.getString("someKey", null));
```
   
 It seems to be working, but adding the dependency to build.gradle and to initialize the storage manually seems wrong.
 Is there any other way to do it ?

**Comment by mrousavy** [comment]
Hey @mtroskot!

Well actually that's probably the way to do it. But I wouldn't recommend it, because 

1. Value Changed Listeners from react-native-mmkv won't notice changes from the native Java module
2. It might be configured incorrectly (e.g. correct ID but wrong encryption key, etc.)

Why do you need to do this?

**Comment by mtroskot** [comment]
@mrousavy we're having some performance issues while decrypting eudcc, so we wanted to move the execution of loading and parsing the TrustList  to the native side

**Comment by mrousavy** [comment]
Hmm, isn't it then better (in terms of flexibility and code-splitting) to just return the value you decrypted from eudcc back to JavaScript?
E.g.:

```ts
const MyDecrypter = NativeModules.MyDecrypter
const decryptedName = await MyDecrypter.eudccDecrypt('whatever')
storage.set('decryptedName', decryptedName)

**Comment by mtroskot** [comment]
Yes, but that would mean we would need to write the decrypt logic for both iOS and Android natively. We only have this issue when scanning the certificate for the first time, every other time it's much faster.

**Comment by mrousavy** [comment]
Sorry, I don't really understand the issue here. You are writing the decrypt logic for both iOS and Android anyways, why not just return the value to JS instead of writing to MMKV natively?

**Comment by mtroskot** [comment]
No, currently everything is in JS written, no native modules were used.

**Comment by mrousavy** [comment]
Right, why do you want to access MMKV from a native module then?

**Comment by mtroskot** [comment]
After geting the TrustList we're storing it in storage alongside with lastUpdate time, so that we don't need to do the TrustList fetching and validation every single time.

**Comment by mrousavy** [comment]
I'm sorry, I don't understand what the issue is. I also have no idea what TrustList is, and what fetching and validation you do 🤷

**Comment by wmonecke** [comment]
@mrousavy We need to process some notifications on the native side since we do some heavy-duty stuff with the notification payloads.

We would like that after filtering/sorting the notifications these would be saved into mmkv so that when the app is opened and JS takes over we can then access these values processed notification payloads.

What approach should we consider here? Any feedback is greatly appreciated.

**Comment by mrousavy** [comment]
Hey - enable multi process mode, then implement the notifications through RN bridge - this isn't quite trivial and I don't have the free time atm to implement this feature and not a lot of people need this :/

**Comment by wmonecke** [comment]
@mrousavy No worries I think this is enough for me to dig that way. I can submit a documentation PR if anyone else needs something similar once I have done it.

**Comment by lfernandezn** [comment]
Hi! I managed to get both the app notification extension and the react-native side of the app use the same mmkv storage. Here's my implementation, any feedback is appreciated.
I added https://github.com/Tencent/MMKV to my app, I followed the https://github.com/Tencent/MMKV/wiki/iOS_tutorial Enabled multi-process and setup MMKV to the target via dynamic linking, as instructed in https://github.com/Tencent/MMKV/wiki/iOS_setup
Then, I tried to setup react-native-mmkv-storage and followed https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/131#issuecomment-878842486 but I couldn't access the same data from the app extension and the react-native side of the app. The issue was the path used was different, since the native version used  [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:myGroupID].path; and the rn version used the first path from NSSearchPathForDirectoriesInDomains. So I created the following patch and now both implementations access the same data.
```
diff --git a/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm b/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm
index 9af089d..d895a3e 100644
--- a/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm
+++ b/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm
@@ -30,10 +30,11 @@ - (instancetype)init
 {
     self = [super init];
     RCTExecuteOnMainQueue(^{
-        NSArray *paths = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory,
-                                                             NSUserDomainMask, YES);
-        NSString *libraryPath = (NSString *)[paths firstObject];
-        NSString *rootDir = [libraryPath stringByAppendingPathComponent:@"mmkv"];
+  NSString *myGroupID = @"group.my.app.group.bundle";
+  // the group dir that can be accessed by App & extensions
+  NSString *groupDir = [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:myGroupID].path;
+  NSString *rootDir = [groupDir stringByAppendingPathComponent:@"mmkv"];
+        NSLog(@"Library path: %@", rootDir);
         rPath = rootDir;
         _secureStorage = [[SecureStorage alloc] init];
         [MMKV initializeMMKV:rootDir];
@@ -706,7 +707,7 @@ static void install(jsi::Runtime &jsiRuntime) {
 }
 
 - (void)migrate {
-    MMKV *kv = [MMKV mmkvWithID:@"mmkvIdStore"];
+    MMKV *kv = [MMKV mmkvWithID:@"mmkvIdStore" mode:MMKVMultiProcess];
     [mmkvInstances setObject:kv forKey:@"mmkvIdStore"];
     if ([kv containsKey:@"mmkvIdData"]) {
         NSMutableDictionary *oldStore =
```
I don't know if this is a good implementation, but it is working for me, any advice/feedback is welcome. Does this look like what you kind of had in mind?

**Comment by wmonecke** [comment]
@mrousavy Does this implementation look kind of coherent to you? If it does maybe we can add a PR to add this to the docs?
