### ISSUE TITLE
[Question] Total storage size?

### ISSUE THREAD

**Issue by PaulOskarSoe** [mrousavy/react-native-mmkv#323]
Hey! 

What is the default total storage size? AsyncStorage has 6 MB of storage by default.

**Comment by ramiel1999** [comment]
yes please

**Comment by LupulescuAlexandru** [comment]
From the official MMKV [FAQ](https://github.com/Tencent/MMKV/wiki/FAQ):

> What're MMKV's limitations?
MMKV works perfectly well in most cases, the size and length of keys and values are unlimited. However, since MMKV caches everything in memory if the total size is too big (like 100M+), App may receive a memory warning. And write speed might slow down when a full write-back is needed.

**Comment by mrousavy** [comment]
MMKV, as the name already says, is a memory-map key-value storage. It is perfect for quickly caching small data (e.g. username/password, private key, session configuration, small settings pairs, etc etc), and since everything happens in-memory it is not recommended to store large amounts of data in there.

I keep my MMKV instances small (probably always under 10 MB, I never measured them), and for larger data I use an actual database like SQLite or WatermelonDB. This is the perfect combination of performance, quick access and scalability.
