### ISSUE TITLE
Question about the limitations

### ISSUE THREAD

**Issue by Stevemoretz** [mrousavy/react-native-mmkv#325]
Hello thank you for this library, I couldn't find information of whether this library is implemented with SQLite or not.

The other famous library has one significant limitation on Android (due to its implementation on SQLite of course) :
https://react-native-async-storage.github.io/async-storage/docs/limits

Which is that you can not store more than 2mb in one single key, I was curious whether that limitation exists on your implementation or not?

Also would be nice to know if there exists a total size limitation or not?

Thank you so much in advance!

**Comment by mrousavy** [comment]
Hey!

MMKV is an in-memory key value storage. This means, it is insanely quick and efficient for small stuff, but anything larger will probably be a slow-down since everything is happening in-memory.

So in short, stuff like "user.refresh-token" or "settings.is-dark" is perfect for MMKV, but stuff like "user.profile-picture-base64" or other big values should be stored in another database (eg SQLite or WatermelonDB) instead.

**Comment by Stevemoretz** [comment]
Thank you for clarification!

**Comment by ramirobg94** [comment]
I used this library to store more or less 0.5KB and I started to have problems
