### ISSUE TITLE
How to get multiple value

### ISSUE THREAD

**Issue by robyhuzwandar** [mrousavy/react-native-mmkv#393]
AsyncStorage have this function

`await AsyncStorage.multiGet(keys);`

how to do this with mmkv?

**Comment by mrousavy** [comment]
Hey! MMKV is a typed storage, whereas AsyncStorage is not.

This means that in AsyncStorage you can only get strings, but in MMKV you can get strings, booleans and numbers - so there is no way to get multiple keys since the type is not known.

If you are 100% sure that all values you store in MMKV are of one type (e.g. string) you can just do:

```ts
const keys = ...
const values = keys.map((key) => storage.getString(key))
```
