### ISSUE TITLE
getString returns empty string for number type keys

### ISSUE THREAD

**Issue by pke** [mrousavy/react-native-mmkv#472]
mmkv store contains a number but when this key is read out via getStringSetting it return an empty string instead of undefined.

1. `storage.set("number", 100)`
2. `storage.getString("number")` returns `""` (empty string)
3. `storage.getNumber("number")` returns correctly `100`

**Comment by mrousavy** [comment]
Yes, this is intended behaviour. MMKV does not store the type of the data, the user is responsible for knowing that. I've thought about creating an abstraction ontop of this to also store the data type, but obviously this will take more store and cost performance as it's runtime type checking.

More explanation if you're interested:

The reason this is intended is because the number `100` is stored as a double (`0x4059000000000000` in hex) and when read as a string (8 bits a char) this is an invalid string, hence `""` (empty string).

**Comment by pke** [comment]
Thanks for the quick response and especially for the details.

But if its an invalid string, why isn't it returned as `undefined` then (like I think I read here in the repo in an example)? 
That's a decission of this lib or the original MMKV implementation?

**Comment by pke** [comment]
Also would this library provide means to supply `defaultValue` to MMKV? Maybe thats a separate issue.

**Comment by mrousavy** [comment]
This is the fault of MMKV, not of my wrapper.
