### ISSUE TITLE
QUESTION: Explain working when react-native new architecture is NOT enabled in my app

### ISSUE THREAD

**Issue by sriadimanav** [mrousavy/react-native-mmkv#597]
how are we able to read data synchronously when NOT using new react-native architecture in app ?
- old architecture uses Bridge (Asynchronous approach) and new architecture uses JSI (Synchronous approach), how does MMKV handles this ? how are we able to read data Synchronously on JS side ?

**Comment by mrousavy** [comment]
RN MMKV uses JSI, no matter if you are on the old arch or on the new arch :)

**Comment by Navipro70** [comment]
It's quite interesting, I've never thinked before, how we can access JSI modules without new architecture (because there are no info passed 2+ years:)

And also, from explanation: "Turbo module is native module that uses JSI", but what is real difference, why Turbo Modules can't be used on old architecture, etc.

Maybe I've missed something?)
