### ISSUE TITLE
Feature: get keys with prefix

### ISSUE THREAD

**Issue by EternalDeiwos** [mrousavy/react-native-mmkv#612]
Hi,

Would it be possible to add the ability to fetch a list of keys with a given prefix? It could be an optional parameter to the `getAllKeys` function.

For example, I would like to do something like this:

```js
store.set(“foo”, “bar”)
store.set(“user.email”, “foo@example.com”)
const userKeys = store.getAllKeys(“user”)
// [“user.email”]
```

**Comment by mrousavy** [comment]
Hey! Thanks for the feature request, but this is not possible to do on the native side because there is no way to filter keys in MMKV's request.
It's quite a light method, so I think the filtering should just be done on the JS side for better intention awareness by being more explicit in code.
Let me know what you think!

**Comment by EternalDeiwos** [comment]
@mrousavy ACK. Thanks for the explanation. The `getAllKeys()` method returns a sorted array so I am basically just using `sortedIndex` from [Lodash](https://lodash.com/docs/4.17.15#sortedIndex) which IIRC is just a binary search.

**Comment by mrousavy** [comment]
Sounds good, yea. I don't think that'd be a perf. concern 👍
