### ISSUE TITLE
Make `Set` and `Get` method consistent

### ISSUE THREAD

**Issue by flixyudh** [mrousavy/react-native-mmkv#629]
I've migrate from `react-native-mmkv-storage` to `react-native-mmkv`,  and I've seen the [Set](https://github.com/mrousavy/react-native-mmkv?tab=readme-ov-file#set) section is possible to create dynamic `datatype` (`boolean`, `string` and `number` for now) but at [Get](https://github.com/mrousavy/react-native-mmkv?tab=readme-ov-file#get) section, I need to defined the `datatype`.

I don't really understand when react-native-mmkv can `set` any `datatype` why it need to use specific `datatype` to `get` the data? it makes more sense for me if I need to specify `datatype` while `set` instead of `get`, but as for now `set` method can use any `datatype`, is it possible to do the same thing with `get` method?

**Comment by mrousavy** [comment]
## Set

When passing a `number` to `set`, I can see that it is a `number`, so the type `number` is implied. 

## Get

When reading something from the storage (which is just bytes/binary), I don't know how the type is stored. There is no type information as you could overwrite it with any type, and it is also more lightweight/performant if it does not have any type information stored. So in this case you need to specify how you interpret the type to be read.

**Comment by flixyudh** [comment]
> When reading something from the storage (which is just bytes/binary), I don't know how the type is stored.

if so, why don't let store all value as `string`? since there's only 3 types (string, number, boolean), I think it's more lightweight/performant because the type always `string` (it would be different if `react-native-mmkv` also can store `Map` and `Array`).

an example of the simplification I was thinking of:

```js
storage.set('user.name', 'Marc') 
// storage.get('user.name') 

storage.set('user.age', '21')
// storage.get('user.age')
// if dev **really** need to convert it as number, use `Number(storage.get('user.age'))` instead.

storage.set('is-mmkv-2fast', 'true')
// for boolean, i think `storage.contains('is-mmkv-2fast')` is enough, don't need for redundant method
```

would you mind considerating it @mrousavy ?

**Comment by mrousavy** [comment]
> if so, why don't let store all value as `string`? since there's only 3 types (string, number, boolean), I think it's more lightweight/performant because the type always `string`

No, why would it be more lightweight or performant to store a number or a boolean as a string?

### 1. Number

 A `number` in JavaScript is represented as a 64-bit float (aka "double"), meaning it takes up 8 bytes.

The number `1` takes up 8 bytes, the number `812735` does take up 8 bytes, the number `541.5357235` takes up 8 bytes, even the number `179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368` is 8 bytes.

Strings in JavaScript are usually 2 bytes or 5 bytes (depending if they are unicode or not), so if you were to represent this as a string, the string `"1"` would be 2 bytes, the string `"812735"` would be 12 bytes, the string `"541.5357235"` would be 22 bytes, and the string `"179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368"` would be 618 bytes. 

It goes without saying that this would be a huge waste of space.

### 2. Boolean

A boolean in JavaScript is represented with 1 byte. The string `"true"` would be 8 bytes, and `"false"` would be 10 bytes. This is another waste of space.

### 3. Efficiency

Reading a single boolean (`00000001` in binary) is much more efficient than reading the binary values of the string, then decoding it into a UTF-8/UTF-16 character sequence. 

Same goes for numbers.

### 4. Practicality

If you store a number or a boolean, you want to store a number or a boolean. Not a string. Example:

```ts
const isDarkMode = storage.getBoolean('is.dark')
const color = isDarkMode ? 'black' : 'white'
```

Now if we had strings:

```ts
const isDarkModeString = storage.getBoolean('is.dark')
const isDarkMode = isDarkModeString == 'true'
const color = isDarkMode ? 'black' : 'white'
```

This would be really annoying as you always need a separate cast. Or what if it is `True` instead of `true`? Or `1` instead of `true`?

---

With all of that said, I think it's pretty obvious that storing every value as a string is not a good idea.

**Comment by mrousavy** [comment]
> for boolean, i think `storage.contains('is-mmkv-2fast')` is enough, don't need for redundant method

This is also not true, lol. What if `is-mmkv-2fast` is `false`? The `contains` method will return `true` then 😄

**Comment by mrousavy** [comment]
> if dev **really** need to convert it as number, use `Number(storage.get('user.age'))` instead.

What else do you want to do with `user.age`? Age is a number, not a string - in 100% of the cases when you store a number you also want to read it as a number, not a string.

**Comment by flixyudh** [comment]
[it was a good insight for me](https://github.com/mrousavy/react-native-mmkv/issues/629#issuecomment-1942109541) because I was not really aware about the byte sizes before. 

> This is also not true, lol. What if `is-mmkv-2fast` is `false`? The `contains` method will return `true` then 😄

maybe because I've playing `AsyncStorage` too long that I keep use `set` and `delete` method for `boolean` purpose 🤔 

since it's all about the byte sizes concern, I can't complain anymore. 🤣
