### ISSUE TITLE
ERROR Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.

### ISSUE THREAD

**Issue by blackMastery** [mrousavy/react-native-mmkv#690]
can i get some help with this issue.
`
Android Bundling complete 65ms
ERROR Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.

Make sure react-native-mmkv is correctly autolinked (run npx react-native config to verify)
Make sure gradle is synced.
Make sure you ran expo prebuild.
Make sure you rebuilt the app., js engine: hermes
`

**Comment by artahadhahd** [comment]
Having the same issue here

**Comment by mrousavy** [comment]
Hey - there is not enough details here for me to take a look at this. The example app here works fine, try it.

Also, I don't know which RNMMKV/RN versions you are using since you didn't post them, but the README tells you the version compatibility.

For RN 0.74+ use react-native-mmkv 3.x.x (beta) and enable the new architecture
For RN 0.73 or lower use react-native-mmkv 2.x.x and disable the new architecture.

If you verified all of this is correct and it still doesn't work, then I still cannot help you without any logs, reproductions, stacktraces or repro apps.

**Comment by divyansh0908nl** [comment]
Hey @mrousavy is flipper still needed?

**Comment by mrousavy** [comment]
no.

**Comment by see2ever** [comment]
maybe is the coinbase's bug:

https://github.com/MobileWalletProtocol/wallet-mobile-sdk/issues/374
