### ISSUE TITLE
Why it can't use mmkv from central maven rather than building from mmkv submodule?

### ISSUE THREAD

**Issue by wood1986** [mrousavy/react-native-mmkv#714]
I have a scenario that my app has a direct dependency on mmkv. This means I am using `implementation 'com.tencent:mmkv:1.3.9'` in the build.gradle on android. I want to use react-native-mmkv for the react-native area mostly. But I cannot exclude a use case that react-native and native will access the same mmkv store. With this situation, my app will have two copy of mmkv. 

iOS is using the cocoapod. If I specify MMKV in the podfile, I believe my app and the react-native-mmkv are using the same mmkv and no duplication.

So my question why this lib needs to build the mmkv from submodule?

**Comment by mrousavy** [comment]
Hey!

This is because react-native-mmkv actually uses MMKV's C++ library, through direct JSI bindings. If you browse the codebase, you can see there is no Java code for accessing MMKV. 

This way, it's faster, and more portable - and we can also fully re-use the code from the iOS codebase.

> iOS is using the cocoapod. If I specify MMKV in the podfile, I believe my app and the react-native-mmkv are using the same mmkv and no duplication

Not true, nope. iOS also uses the C++ submodule codebase.

**Comment by wood1986** [comment]
@mrousavy 

If iOS use c++ submodule, why the react-native-mmkv.podspec has this line

![image](https://github.com/user-attachments/assets/bf299181-57d3-4ffa-a0cc-93aa739c4201)

**Comment by mrousavy** [comment]
> If iOS use c++ submodule, why the react-native-mmkv.podspec has this line.

You are using the "old" react-native-mmkv (V2). The new one (V3) has been using MMKV from source since a few months now.

> Now the app has two copy of MMKV. One is from central maven. The other is from this library. Does it sound right to you?

No, it does not sound right to me.

> I know this but you are not answering my question.

Do you mean the original question _"So my question why this lib needs to build the mmkv from submodule?"_?

Then I already gave you an answer to that.

![image](https://github.com/user-attachments/assets/81ca4e27-da86-4c2d-aca3-61815421deb6)

---
With that said, you're probably asking me now how to combine react-native-mmkv and the Gradle/Podspec MMKV dependencies.

My answer is; I don't know. That's tricky.

If you inspect the Gradle dependency, you'll see that the C++ code is not in there as a prefab, so I cannot use it. I need to build it from source. That is also much more lightweight for everyone else, since we don't need Java/JNI bindings or ObjC bindings - just pure C++, as fast as it can be.

**Comment by wood1986** [comment]
Just FYI: ![image](https://github.com/user-attachments/assets/a93cced3-46ef-4d50-ad2d-5356d1ccf199)

**Comment by mrousavy** [comment]
yup, would be cool to build C++ MMKV as a shared lib (so)
